// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaGQkE4GB2b2RuDB3HqpaJemkVakHm-0M',
    appId: '1:462372264606:web:1682e0c068a5efdcf7798f',
    messagingSenderId: '462372264606',
    projectId: 'tc2007b-a5487',
    authDomain: 'tc2007b-a5487.firebaseapp.com',
    storageBucket: 'tc2007b-a5487.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YqzbkEp56bUykrMR3mI3bAkwIwgwIuM',
    appId: '1:462372264606:android:1b79b51ef48ee150f7798f',
    messagingSenderId: '462372264606',
    projectId: 'tc2007b-a5487',
    storageBucket: 'tc2007b-a5487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSiG-46durMUzWWw-Ab2McFG32mwmGWU',
    appId: '1:462372264606:ios:347649d98328c9e2f7798f',
    messagingSenderId: '462372264606',
    projectId: 'tc2007b-a5487',
    storageBucket: 'tc2007b-a5487.firebasestorage.app',
    iosBundleId: 'com.example.bamx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSiG-46durMUzWWw-Ab2McFG32mwmGWU',
    appId: '1:462372264606:ios:347649d98328c9e2f7798f',
    messagingSenderId: '462372264606',
    projectId: 'tc2007b-a5487',
    storageBucket: 'tc2007b-a5487.firebasestorage.app',
    iosBundleId: 'com.example.bamx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaGQkE4GB2b2RuDB3HqpaJemkVakHm-0M',
    appId: '1:462372264606:web:79bfa145b95145eaf7798f',
    messagingSenderId: '462372264606',
    projectId: 'tc2007b-a5487',
    authDomain: 'tc2007b-a5487.firebaseapp.com',
    storageBucket: 'tc2007b-a5487.firebasestorage.app',
  );
}
